### ISSUE TITLE
Add a way to get the stem of a filename

### ISSUE THREAD

**Issue by sgpthomas** [rachitnigam/runt#5]
For tests where you want to run multiple commands to generate the test output, it would be very convenient to have a way to get the filename without the file extension. I don't exactly know what the syntax would be it would look something like this:

```toml
[[tests]]
name = "Verilog tests"
paths = [ "tests/verilog/*.futil" ]
cmd = "./target/debug/futil {}.futil -l ./primitives/std.lib -b verilog | {}.v"
```
where the command would be replaced with
```toml
cmd = "./target/debug/futil tests/verilog/seq.futil -l ./primitives/std.lib -b verilog | tests/verilog/seq.v"
```

**Comment by rachitnigam** [comment]
You can use the `basename` command to extract the name of file:
```bash
basename -s .toml runt.toml  # returns: runt
```

Let me know if that is insufficient.

**Comment by sgpthomas** [comment]
This is not really good enough because `basename -s test/test.s` returns `test` not, `test/test`. This is why I was doing funky parameter expansion stuff for the verilator testing:
```
full={}; f=${full%.*}; make $f.res 
```

**Comment by rachitnigam** [comment]
That seems fine. I don't really want to add more syntax than needed for runt configurations. The `{}` stuff is from `parallel` and even that is more than what I want.

Also, with multiline strings, it really won't look that bad:
```toml
cmd = """
full={}
stem=${full%.*}
make $stem.res
"""
```
