### ISSUE TITLE
Allow setup and clean commands

### ISSUE THREAD

**Issue by sgpthomas** [rachitnigam/runt#6]
If you want to run a makefile to generate the file to do diff testing on, you are forced to make the command look like:
```toml
cmd = "make {} 1>/dev/null 2>/dev/null; cat {}; rm {}"
```
It would be nice if you could instead do:
```toml
setup = "make {}"
cmd = "cat {}"
cleanup = "rm {}"
```
Eventually, you could imagine automating the cleanup to remove any files generated during the `setup` command.
