### ISSUE TITLE
Option to build project before running

### ISSUE THREAD

**Issue by sgpthomas** [rachitnigam/runt#7]
It would be nice to have a field in the config to specify how to build a binary. It would look something like this:
```toml
[[tests]]
...
build = “cargo build”
...
```
Runt would run this command once before running all the file tests.
